# Generated by Django 3.0.8 on 2020-07-28 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vistas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fecha',
        ),
    ]
